#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cd bin/
tar cvzf ../dist/artifacts/rancher-vxlan-${ARCH}-${VERSION}.tar.gz .

echo "Built rancher-vxlan-${ARCH}-${VERSION}.tar.gz"
